# Generated by Django 5.0.4 on 2024-04-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_rename_q_id_comment_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_a', models.PositiveSmallIntegerField()),
                ('subject_b', models.PositiveSmallIntegerField()),
                ('subject_c', models.PositiveSmallIntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark_student', to='user.teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_teacher', to='user.teacher')),
            ],
        ),
    ]
