# Generated by Django 5.0.4 on 2024-04-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment_content_hod_experience_question_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='q_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='management',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user_id',
            new_name='user',
        ),
    ]
