# Generated by Django 5.0.4 on 2024-04-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='atendee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='atendee_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
